//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripXpert.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Image
    {
        [Key]
        public int ImageID { get; set; }
        public Nullable<int> AttractionID { get; set; }
        public int DestinationID { get; set; }
        public string Description { get; set; }
        public string Author { get; set; }
        public string ImageURL { get; set; }
        public string Title { get; set; }
        public string FolderName { get; set; }

        public virtual Attraction Attraction { get; set; }
        public virtual Destination Destination { get; set; }
    }
}
