//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripXpert.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TourInfo
    {
        [Key]
        public int InfoID { get; set; }
        public int DestinationID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> PerPersonSharing { get; set; }
        public Nullable<int> PerSingleOccupancy { get; set; }
        public Nullable<int> PerChild { get; set; }
        public Nullable<short> Duration { get; set; }
    
        public virtual Destination Destination { get; set; }
    }
}
